[package]
name = "rustls-import-keys"
version = "0.1.0"
edition = "2021"

[dependencies]
der = "0.7"
libcrux = { git = "https://github.com/kraemv/libcrux", rev = "0d45b3908aaa267ae0408428196c661492af9c70" }
pkcs8 = { version = "0.10.2", features = ["pem"] }
pki-types = { package = "rustls-pki-types", version = "1" }
rustls = { version = "0.23.18" }
rustls-libcrux-provider = { workspace = true }
webpki = { package = "rustls-webpki", version = "0.102", features = [
    "alloc", "aws_lc_rs",
], default-features = false }
