[package]
name = "rustls-import-keys"
version = "0.1.0"
edition = "2021"

[dependencies]
der = { git = "https://github.com/kraemv/formats", features = ["pem"]}
libcrux = { git = "https://github.com/kraemv/libcrux", rev = "7668897" }
pkcs8 = { git = "https://github.com/kraemv/formats", features = ["pem"]}
x509-cert = { git = "https://github.com/kraemv/formats", default-features = false }
pki-types = { package = "rustls-pki-types", version = "1" }
rustls = { version = "0.23.18" }
rustls-libcrux-provider = { workspace = true }
webpki = { package = "rustls-webpki", version = "0.102", features = [
    "alloc", "aws_lc_rs",
], default-features = false }
