[package]
name = "rustls-import-keys"
version = "0.1.0"
edition = "2021"

[dependencies]
der = "0.7"
libcrux = { git = "https://github.com/kraemv/libcrux", rev = "d3ab6adc11ec2f104c2e4ee7ee145eef3519368c" }
pkcs8 = { version = "0.10.2", features = ["pem"] }
pki-types = { package = "rustls-pki-types", version = "1" }
rustls = { version = "0.23.18" }
rustls-libcrux-provider = { workspace = true }
webpki = { package = "rustls-webpki", version = "0.102", features = [
    "alloc", "aws_lc_rs",
], default-features = false }
