[workspace]
members = ["agent-setup", "demo-server", "libcrux-provider"]

resolver = "2"

[workspace.dependencies]
rustls-libcrux-provider = { path = "libcrux-provider" }
libcrux = { git = "https://github.com/kraemv/libcrux", rev = "3f655bafd" }
# libcrux = { path = "/home/vincent/libcrux" }

[profile.bench]
codegen-units = 1
lto = true
