[package]
name = "agent-keys"
version = "0.1.0"
edition = "2021"

[dependencies]
base64ct = "1.8.3"
der = { git = "https://github.com/kraemv/formats", rev = "c2da52f7", features = ["pem"]}
libcrux = { git = "https://github.com/kraemv/libcrux", rev = "7668897" }
pkcs8 = { git = "https://github.com/kraemv/formats" , rev = "c2da52f7", features = ["pem"]}
x509-cert = { git = "https://github.com/kraemv/formats", rev = "c2da52f7", default-features = false }
pki-types = { package = "rustls-pki-types", version = "1" }
rand_core = "0.9.5"
rustls = { version = "0.23.36" }
rustls-libcrux-provider = { workspace = true }
sec1 = { version = "0.7.3", features = ["alloc", "point", "der"] }
webpki = { package = "rustls-webpki", version = "0.103", features = [
    "alloc", 
], default-features = false }
